/* GENERATED by scripts/megacity-urls-sync.mjs from worker/studio/urls.js. Do not edit.
   window.MCUrls: the site's own scripts ask it for links, so one page works
   at /templates/megacity-<slug> on the demo host and at root paths on
   megacityproperties.co.uk. */
(function () {
  "use strict";
const DEMO_HOSTS = /^(www\.)?billydigitals\.com$|^localhost$|^127\.0\.0\.1$/i;
const FALLBACK_HOST = "www.megacityproperties.co.uk";

/* static page slug (the part after "megacity-") -> path on the client domain.
   Old-site paths are reused wherever the page is the same thing, so those
   addresses never change; everything else 301s (LEGACY_REDIRECTS below). */
const ROOT_MAP = {
  "skyline": "/",
  "properties": "/lettings",
  "for-landlords": "/landlords",
  "renting": "/tenants",
  "about-us": "/about-us",
  "contact-us": "/contact-us",
  "valuation": "/valuation",
  "journal": "/journal",
  "tenant-find": "/tenant-find",
  "rent-collection": "/rent-collection",
  "fully-managed": "/fully-managed",
  "switch": "/switch",
  "hmo": "/hmo",
  "maintenance": "/maintenance",
  "compliance": "/compliance",
  "tools": "/tools",
  "privacy": "/privacy-policy",
  "terms": "/terms",
  "tenant-application-form": "/tenant-application-form",
  "studio": "/studio",
};
const PATH_TO_SLUG = {};
for (const k in ROOT_MAP) PATH_TO_SLUG[ROOT_MAP[k]] = k;

/* the hand-built pages, in sitemap order */
const PUBLIC_STATIC_SLUGS = ["skyline", "properties", "for-landlords", "tenant-find", "rent-collection", "fully-managed", "switch", "hmo", "maintenance", "compliance", "renting", "valuation", "tools", "journal", "about-us", "contact-us", "privacy", "terms", "tenant-application-form"];
/* the five hand-built listing pages: the fallback while the database is empty */
const STATIC_LET_SLUGS = ["denmark-road", "ladywell-point", "room-3", "room-5", "room-7"];
/* old-site /property/<id>/ numbers -> our slugs, for the listings we know */
const LEGACY_LISTINGS = { "226": "denmark-road", "225": "ladywell-point", "102": "room-7", "108": "room-3", "110": "room-5" };
/* root paths a Studio page may never take */
const RESERVED_ROOT_SLUGS = ["lettings", "landlords", "tenants", "privacy-policy", "tenant-application-form", "let", "property", "api", "media", "billy360", "templates", "sitemap", "sitemap.xml", "robots", "robots.txt", "images", "css", "js", "free-valuation", "testimonials", "register", "blog", "sales", "buyers", "vendors", "commercial", "index", "home", "404", "favicon.ico", "apple-touch-icon.png"];

function withFrag(p, frag) { return frag ? p + (frag.charAt(0) === "#" ? frag : "#" + frag) : p; }
function pagePath(mode, slug, frag) {
  const s = String(slug || "skyline");
  return withFrag(mode === "root" ? (Object.prototype.hasOwnProperty.call(ROOT_MAP, s) ? ROOT_MAP[s] : "/" + s) : "/templates/megacity-" + s, frag);
}
function listingPath(mode, id) { return (mode === "root" ? "/let/" : "/templates/megacity-let-") + String(id); }
function studioPath(mode, hash) { return (mode === "root" ? "/studio" : "/templates/megacity-studio") + (hash || ""); }
function assetPath(rel) { return "/templates/" + String(rel || "").replace(/^\/+/, ""); }

/* One link as written in the HTML -> the path it should have in the given
   mode. Absolute, external, scheme-bearing and fragment-only links are
   untouched; in demo mode nothing changes because relative links already
   resolve inside /templates/. */
function rewriteHref(v, mode) {
  if (v == null) return v;
  const s = String(v).trim();
  if (!s || /^(#|\/|data:|javascript:|[a-z][a-z0-9+.-]*:)/i.test(s) || mode !== "root") return v;
  let path = s.replace(/^(\.\/)+/, ""), frag = "", query = "";
  const hi = path.indexOf("#"); if (hi >= 0) { frag = path.slice(hi); path = path.slice(0, hi); }
  const qi = path.indexOf("?"); if (qi >= 0) { query = path.slice(qi); path = path.slice(0, qi); }
  path = path.replace(/\.html$/, "");
  let m, out;
  if (path === "megacity-sitemap.xml") out = "/sitemap.xml";
  else if ((m = /^megacity-let-([a-z0-9-]+)$/.exec(path))) out = listingPath("root", m[1]);
  else if (path === "megacity-studio") out = "/studio";
  else if (/^megacity-[a-z0-9-]+\.(css|js|json|map|xml)$/.test(path)) out = "/templates/" + path;
  else if ((m = /^megacity-([a-z0-9-]+)$/.exec(path))) out = pagePath("root", m[1]);
  else out = "/templates/" + path;                     // assets/…, vendor/…: still served from there
  return out + query + frag;
}
function rewriteSrcset(v, mode) {
  if (v == null || mode !== "root") return v;
  return String(v).split(/\s*,\s*/).map((part) => {
    const bits = part.trim().split(/\s+/);
    if (!bits[0]) return part;
    bits[0] = rewriteHref(bits[0], mode);
    return bits.join(" ");
  }).join(", ");
}
function rewriteStyle(v, mode) {
  if (v == null || mode !== "root") return v;
  return String(v).replace(/url\(\s*(['"]?)([^'")]+)\1\s*\)/g, (all, q, u) => "url(" + q + rewriteHref(u, mode) + q + ")");
}
/* a normalised root path (no trailing slash) -> what it is */
function resolveRoot(path) {
  if (path === "/") return { kind: "home", slug: "skyline" };
  if (path === "/studio") return { kind: "studio", slug: "studio" };
  let m;
  if ((m = /^\/let\/([a-z0-9-]{1,80})$/.exec(path))) return { kind: "listing", slug: m[1] };
  if (Object.prototype.hasOwnProperty.call(PATH_TO_SLUG, path)) return { kind: "page", slug: PATH_TO_SLUG[path] };
  if ((m = /^\/([a-z0-9]+(?:-[a-z0-9]+)*)$/.exec(path))) return { kind: "cms", slug: m[1] };
  return null;
}
/* the page slug for a pathname in either mode ("valuation"; "let-<id>" for a listing) */
function slugOfPath(pathname, mode) {
  const p = String(pathname || "").replace(/\/+$/, "") || "/";
  if (mode === "root") {
    if (Object.prototype.hasOwnProperty.call(PATH_TO_SLUG, p)) return PATH_TO_SLUG[p];
    const m = /^\/let\/([a-z0-9-]+)$/.exec(p);
    return m ? "let-" + m[1] : p.slice(1);
  }
  const m = /^\/templates\/megacity-([a-z0-9-]+?)(?:\.html)?$/.exec(p);
  return m ? m[1] : "";
}
  function browserMode() {
    return location.pathname.indexOf("/templates/") === 0 || DEMO_HOSTS.test(location.hostname) ? "demo" : "root";
  }
  window.MCUrls = {
    mode: browserMode,
    href: function (v) { return rewriteHref(v, browserMode()); },
    page: function (slug, frag) { return pagePath(browserMode(), slug, frag); },
    listing: function (id) { return listingPath(browserMode(), id); },
    studio: function (hash) { return studioPath(browserMode(), hash); },
    pagePrefix: function () { return browserMode() === "root" ? "/" : "/templates/megacity-"; },
    slugOf: function (p) { return slugOfPath(p, browserMode()); },
    ROOT_MAP: ROOT_MAP, LEGACY_LISTINGS: LEGACY_LISTINGS
  };
})();
